# Generated by Django 2.0.4 on 2018-12-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_websitelogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitelogo',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/website_logo'),
        ),
    ]
