# Generated by Django 2.0.4 on 2018-12-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_auto_20181218_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitelogo',
            name='image',
            field=models.ImageField(upload_to='profile_image', verbose_name='img'),
        ),
    ]
