# Generated by Django 2.0.4 on 2018-12-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_auto_20181219_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitelogo',
            name='image',
            field=models.ImageField(blank=True, upload_to='vanilla_arcade/profile_image'),
        ),
    ]
