# Generated by Django 2.0.4 on 2018-12-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_auto_20181219_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitelogo',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
