# Generated by Django 2.0.4 on 2018-12-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0011_auto_20181219_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitelogo',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/uploads'),
        ),
    ]
