# Generated by Django 2.0.4 on 2018-12-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0013_auto_20181219_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitelogo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
