# Generated by Django 2.0.4 on 2018-12-21 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0015_auto_20181220_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='websitelogo',
            old_name='image',
            new_name='img',
        ),
    ]
