# Generated by Django 2.0.4 on 2018-12-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0016_auto_20181221_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitelogo',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/img/default.png'),
        ),
    ]
