# Generated by Django 2.0.4 on 2018-12-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0018_auto_20181221_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitelogo',
            name='img',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='uploads'),
        ),
    ]
